# Generated by Django 3.1.3 on 2020-11-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
